export {
  LISTING_CONDITION_NEW,
  LISTING_CONDITION_NOT_APPLICABLE,
  LISTING_CONDITION_USED,
  LISTING_TYPE_PRODUCT,
  LISTING_TYPE_SERVICE,
} from "@/src/entities/listing";

export const ATTRIBUTE_TYPE_TEXT = 1;
export const ATTRIBUTE_TYPE_NUMBER = 2;
export const ATTRIBUTE_TYPE_BOOLEAN = 3;
export const ATTRIBUTE_TYPE_SELECT = 4;
export const ATTRIBUTE_TYPE_MULTISELECT = 5;
export const ATTRIBUTE_TYPE_DATE = 6;
